### ISSUE TITLE
Run Terraform failed

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-spring-apps-landing-zone-accelerator#190]
1. when I run 
```terraform plan -out my.plan --var-file ../parameters.tfvars``` 
 from https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/blob/main/Scenarios/ASA-Secure-Baseline/Terraform/07-LZ-AppGateway.md
failed with: 
![image](https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/assets/92105726/a21fd7c0-cbca-4d9a-9e17-1679c175d4e2)

**Comment by Netyyyy** [comment]
2. when run `terraform init`
![image](https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/assets/92105726/c39bd2e6-6533-4b2f-9170-c29e004420d0)
failed with :
![image](https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/assets/92105726/f6f9aa23-087e-4585-bae9-dcdaa9c4c15e)
 seems all variables.tf files have the same problem.

**Comment by Netyyyy** [comment]
Hi all, Any updates for those?

**Comment by jeffpaineMS** [comment]
> 1. when I run
>    `terraform plan -out my.plan --var-file ../parameters.tfvars`
>    from https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/blob/main/Scenarios/ASA-Secure-Baseline/Terraform/07-LZ-AppGateway.md
>    failed with:
>    ![image](https://user-images.githubusercontent.com/92105726/240538726-a21fd7c0-cbca-4d9a-9e17-1679c175d4e2.png)

Hello @Netyyyy

When deploying the 07-LZ-AppGateway you must provide a certificate in PFX format and comfigure the parameters.tfvars "07 Application Gateway" section appropriately for your certificate and backend pool information.

The particular error you're seeing here is about "certfilename" variable not being populated in the parameters.tfvars file. This value is commented out be default as the AppGateway is an optional component.

Hope that helps.

**Comment by jeffpaineMS** [comment]
> 2. when run `terraform init`
>    ![image](https://user-images.githubusercontent.com/92105726/241097638-c39bd2e6-6533-4b2f-9170-c29e004420d0.png)
>    failed with :
>    ![image](https://user-images.githubusercontent.com/92105726/241097695-f6f9aa23-087e-4585-bae9-dcdaa9c4c15e.png)
>    seems all variables.tf files have the same problem.

Hello @Netyyyy,

The error you are seeing here is related to the "name_prefix" variable, we restrict this variables length to 10 characters to control the size of resource names that are created using this variable.

Can you check the value that is set in the "parameters.tfvars" file and make sure it's less than or equal to 10 characters in length? Here I've set mine to "springent".
<img width="483" alt="image" src="https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/assets/114940083/38dc3956-31c6-46dc-b93c-b8b7f5fd6d88">

**Comment by Netyyyy** [comment]
> > 2. when run `terraform init`
> >    ![image](https://user-images.githubusercontent.com/92105726/241097638-c39bd2e6-6533-4b2f-9170-c29e004420d0.png)
> >    failed with :
> >    ![image](https://user-images.githubusercontent.com/92105726/241097695-f6f9aa23-087e-4585-bae9-dcdaa9c4c15e.png)
> >    seems all variables.tf files have the same problem.
> 
> Hello @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor,
> 
> The error you are seeing here is related to the "name_prefix" variable, we restrict this variables length to 10 characters to control the size of resource names that are created using this variable.
> 
> Can you check the value that is set in the "parameters.tfvars" file and make sure it's less than or equal to 10 characters in length? Here I've set mine to "springent". <img alt="image" width="483" src="https://user-images.githubusercontent.com/114940083/242020119-38dc3956-31c6-46dc-b93c-b8b7f5fd6d88.png">

I didn't change `name_prefix`, 
![image](https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/assets/92105726/bd8aec36-0a25-40d2-8eb6-558ac642e735)
and I modified `error_message` to start with a capital letter , it fixed
![image](https://github.com/Azure/azure-spring-apps-landing-zone-accelerator/assets/92105726/79d04e44-01c1-4684-9f12-e548ce3f5f1d)

**Comment by luisfeliz79** [comment]
Hi @Netyyyy, is it ok to close this issue?   Sounds like you got past the challenges, let us know! Thank you.
